server:
  port: 8090
spring:
  application:
    name: post-service
  profiles:
    active: dev
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8071/}"

management:
  endpoints:
    web:
      exposure:
        include: "*"
