services:
  configserver:
    image: "thanhcometodream/config-server:s1"
    container_name: config-server-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 3s
      timeout: 5s
      retries: 2
      start_period: 3s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "thanhcometodream/eurekaserver:s1"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 3s
      timeout: 5s
      retries: 2
      start_period: 3s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  user-service:
    image: "thanhcometodream/user-service:s1"
    container_name: user-service-ms
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 9s
      timeout: 5s
      retries: 3
      start_period: 5s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "user-service"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  post-service:
    image: "thanhcometodream/post-service:s1"
    container_name: post-service-ms
    ports:
      - "8090:8090"
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 9s
      timeout: 5s
      retries: 3
      start_period: 5s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "post-service"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  noti-service:
    image: "thanhcometodream/noti-service:s1"
    container_name: noti-service-ms
    ports:
      - "9000:9000"
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 9s
      timeout: 5s
      retries: 3
      start_period: 5s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "noti-service"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  message-service:
    image: "thanhcometodream/message-service:s1"
    container_name: message-service-ms
    ports:
      - "9010:9010"
    healthcheck:
      test: "curl --fail --silent localhost:9010/actuator/health/readiness | grep UP || exit 1"
      interval: 9s
      timeout: 5s
      retries: 3
      start_period: 5s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "message-service"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  gatewayserver:
    image: "thanhcometodream/gateway-server:s1"
    container_name: gateway-server-ms
    ports:
      - "8072:8072"
    depends_on:
      user-service:
        condition: service_healthy
      post-service:
        condition: service_healthy
      noti-service:
        condition: service_healthy
      message-service:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
    extends:
      file: common-config.yml
      service: microservice-eureka-config
networks:
  socialVNetwork:
    driver: "bridge"
