server:
  port: 8080
spring:
  application:
    name: "user-service"
  profiles:
    active: "dev"
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8071/}"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "user-service"
    description: "Service involve User Info"
    version: "1.0.0"